from enum import StrEnum

class TokenType(StrEnum):
  ACCESS = "access"
  REFRESH = "refresh"

class UserStatus(StrEnum):
  ACTIVE = "active"
  INACTIVE = "inactive"
  LOCKED = "locked"

class PermissionKey(StrEnum):
  IDENTITY_READ = "identity.read"
  IDENTITY_MANAGE = "identity.manage"
  ORGANIZATION_READ = "organization.read"
  ORGANIZATION_MANAGE = "organization.manage"
  ORGANIZATION_MEMBERS_MANAGE = "organization.members.manage"
  PROJECT_READ = "project.read"
  PROJECT_CREATE = "project.create"
  PROJECT_UPDATE = "project.update"
  PROJECT_DELETE = "project.delete"
  SUBSCRIPTION_READ = "subscription.read"
  SUBSCRIPTION_MANAGE = "subscription.manage"
  SUBSCRIPTION_BILLING_MANAGE = "subscription.billing.manage"
  DRAWING_READ = "drawing:read"
  DRAWING_CREATE = "drawing:create"
  DRAWING_DELETE = "drawing:delete"
  BOQ_UPDATE = "boq:update"
  BOQ_APPROVE = "boq:approve"
  MATERIAL_LIBRARY_MANAGE = "material_library:manage"
  WHATSAPP_CHANNEL_MANAGE = "whatsapp.channel.manage"
  SITE_PHOTO_READ = "site_photo.read"
  SITE_PHOTO_MANAGE = "site_photo.manage"
  PROGRESS_CLAIM_READ = "progress_claim:read"
  PROGRESS_CLAIM_CREATE = "progress_claim:create"
  PROGRESS_CLAIM_UPDATE = "progress_claim:update"
  PROGRESS_CLAIM_SUBMIT = "progress_claim:submit"
  PROGRESS_CLAIM_REVIEW = "progress_claim:review"
  PHOTO_BOQ_LINK_READ = "photo_boq_link:read" 
  PHOTO_BOQ_LINK_MANAGE = "photo_boq_link:manage"