"""field_add_boq_versions

Revision ID: 015389ebd02b
Revises: 14cba4c36a9c
Create Date: 2026-10-08 15:33:25.658061
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '015389ebd02b'
down_revision: Union[str, Sequence[str], None] = '14cba4c36a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boq_items', sa.Column('rate_book_id', sa.UUID(), nullable=True))
    op.add_column('boq_items', sa.Column('base_rate', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('boq_items', sa.Column('escalation_factor', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('boq_items', sa.Column('rate_resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('boq_items', 'rate_source',
      existing_type=postgresql.ENUM('LIBRARY', 'AI_SUGGESTED', 'MANUAL', name='boq_item_rate_source'),
      type_=sa.Enum('LIBRARY', 'AI_SUGGESTED', 'MANUAL', 'PROJECT_OVERRIDE', 'RATE_BOOK', name='boq_item_rate_source', native_enum=False, length=20),
      existing_nullable=True)
    op.create_foreign_key('fk_boq_items_rate_book', 'boq_items', 'rate_books', ['rate_book_id'], ['id'], ondelete='SET NULL')
    op.add_column('boq_snapshot_items', sa.Column('base_rate', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('boq_snapshot_items', sa.Column('escalation_factor', sa.Numeric(precision=8, scale=4), nullable=True))
    op.add_column('boq_snapshot_items', sa.Column('rate_resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('boq_snapshot_items', sa.Column('effective_from', sa.Date(), nullable=True))
    op.drop_column('boq_snapshot_items', 'rate_source')
    op.drop_column('boq_snapshot_items', 'unit_rate')
    op.add_column('boq_versions', sa.Column('pricing_meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('boq_versions', sa.Column('priced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('labour_rates', sa.Column('work_item_code', sa.String(length=50), nullable=True))
    op.add_column('labour_rates', sa.Column('effective_from', sa.Date(), nullable=True))
    op.add_column('material_library', sa.Column('work_item_code', sa.String(length=50), nullable=True))
    op.add_column('material_library', sa.Column('effective_from', sa.Date(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_library', 'effective_from')
    op.drop_column('material_library', 'work_item_code')
    op.drop_column('labour_rates', 'effective_from')
    op.drop_column('labour_rates', 'work_item_code')
    op.drop_column('boq_versions', 'priced_at')
    op.drop_column('boq_versions', 'pricing_meta')
    op.add_column('boq_snapshot_items', sa.Column('unit_rate', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('boq_snapshot_items', sa.Column('rate_source', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('boq_snapshot_items', 'effective_from')
    op.drop_column('boq_snapshot_items', 'rate_resolution')
    op.drop_column('boq_snapshot_items', 'escalation_factor')
    op.drop_column('boq_snapshot_items', 'base_rate')
    op.drop_constraint('fk_boq_items_rate_book', 'boq_items', type_='foreignkey')
    op.alter_column('boq_items', 'rate_source',
               existing_type=sa.Enum('LIBRARY', 'AI_SUGGESTED', 'MANUAL', 'PROJECT_OVERRIDE', 'RATE_BOOK', name='boq_item_rate_source', native_enum=False, length=20),
               type_=postgresql.ENUM('LIBRARY', 'AI_SUGGESTED', 'MANUAL', name='boq_item_rate_source'),
               existing_nullable=True)
    op.drop_column('boq_items', 'rate_resolution')
    op.drop_column('boq_items', 'escalation_factor')
    op.drop_column('boq_items', 'base_rate')
    op.drop_column('boq_items', 'rate_book_id')
    # ### end Alembic commands ###