"""reinfor_bar_bendi_sched

Revision ID: 0cbac138a2a1
Revises: 2202fbeab39d
Create Date: 2026-10-05 18:02:42.407046
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0cbac138a2a1'
down_revision: Union[str, Sequence[str], None] = '2202fbeab39d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bar_sizes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('standard', sa.String(length=60), nullable=False),
    sa.Column('designation', sa.String(length=20), nullable=False),
    sa.Column('grade', sa.String(length=30), server_default='ALL', nullable=False),
    sa.Column('nominal_dia_mm', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('unit_weight_kg_m', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('nominal_dia_mm > 0', name='ck_bar_sizes_dia'),
    sa.CheckConstraint('unit_weight_kg_m > 0', name='ck_bar_sizes_weight'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'standard', 'designation', 'grade', name='uq_bar_sizes_org_std_desig_grade')
    )
    op.create_index('ix_bar_sizes_org', 'bar_sizes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bar_sizes_organization_id'), 'bar_sizes', ['organization_id'], unique=False)
    op.create_index('uq_bar_sizes_system_std_desig_grade', 'bar_sizes', ['standard', 'designation', 'grade'], unique=True, postgresql_where=sa.text('organization_id IS NULL'))
    op.create_table('rebar_shapes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('standard', sa.String(length=60), nullable=True),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('bend_spec', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('bend_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('hook_ends', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bend_count >= 0', name='ck_rebar_shapes_bend_count'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_rebar_shapes_org_code')
    )
    op.create_index('ix_rebar_shapes_org', 'rebar_shapes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_rebar_shapes_organization_id'), 'rebar_shapes', ['organization_id'], unique=False)
    op.create_index('uq_rebar_shapes_system_code', 'rebar_shapes', ['code'], unique=True, postgresql_where=sa.text('organization_id IS NULL'))
    op.create_table('rebar_schedule_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('schedule_import_id', sa.UUID(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('member_mark', sa.String(length=100), nullable=True),
    sa.Column('mark', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('shape_code', sa.String(length=40), nullable=True),
    sa.Column('shape_params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('designation', sa.String(length=20), nullable=True),
    sa.Column('dia_mm', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('grade', sa.String(length=30), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('spacing_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cut_len_mm', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('declared_total_kg', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('level_id', sa.UUID(), nullable=True),
    sa.Column('matched_element_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), server_default='0.5', nullable=False),
    sa.Column('review_status', sa.String(length=10), server_default='PENDING', nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("review_status <> 'CONFIRMED' OR (mark IS NOT NULL AND dia_mm IS NOT NULL AND count IS NOT NULL AND (cut_len_mm IS NOT NULL OR shape_code IS NOT NULL))", name='ck_rebar_schedule_rows_confirmed_complete'),
    sa.CheckConstraint("review_status IN ('PENDING','CONFIRMED','REJECTED')", name='ck_rebar_schedule_rows_review_status'),
    sa.CheckConstraint('(count IS NULL OR count >= 0) AND (cut_len_mm IS NULL OR cut_len_mm >= 0)', name='ck_rebar_schedule_rows_non_negative'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_rebar_schedule_rows_confidence'),
    sa.CheckConstraint('row_no >= 1', name='ck_rebar_schedule_rows_row_no'),
    sa.ForeignKeyConstraint(['level_id'], ['building_levels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_element_id'], ['drawing_elements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_import_id', 'organization_id'], ['schedule_imports.id', 'schedule_imports.organization_id'], name='fk_rebar_schedule_rows_import_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_rebar_schedule_rows_id_org'),
    sa.UniqueConstraint('schedule_import_id', 'row_no', name='uq_rebar_schedule_rows_import_row')
    )
    op.create_index('ix_rebar_schedule_rows_import', 'rebar_schedule_rows', ['schedule_import_id'], unique=False)
    op.create_index('ix_rebar_schedule_rows_org_status', 'rebar_schedule_rows', ['organization_id', 'review_status'], unique=False)
    op.create_table('rebar_bar_marks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('solid_id', sa.UUID(), nullable=False),
    sa.Column('element_id', sa.UUID(), nullable=True),
    sa.Column('level_id', sa.UUID(), nullable=True),
    sa.Column('mark', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('shape_code', sa.String(length=40), nullable=False),
    sa.Column('shape_params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('designation', sa.String(length=20), nullable=True),
    sa.Column('dia_mm', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('grade', sa.String(length=30), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('spacing_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cut_len_mm', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('stock_len_mm', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('pieces', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('lap_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('lap_len_mm', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('total_len_m', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit_weight_kg_m', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_kg', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('review_status', sa.String(length=20), server_default='OK', nullable=False),
    sa.Column('schedule_row_id', sa.UUID(), nullable=True),
    sa.Column('trace', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('engine_version', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provenance <> 'RULE_ESTIMATE' OR review_status = 'REVIEW_REQUIRED'", name='ck_rebar_bar_marks_estimate_needs_review'),
    sa.CheckConstraint("provenance IN ('IFC_EXACT','SCHEDULE_IMPORT','MANUAL','RULE_ESTIMATE')", name='ck_rebar_bar_marks_provenance'),
    sa.CheckConstraint("review_status IN ('OK','REVIEW_REQUIRED','WAIVED')", name='ck_rebar_bar_marks_review_status'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_rebar_bar_marks_confidence'),
    sa.CheckConstraint('cut_len_mm >= 0 AND total_len_m >= 0 AND total_kg >= 0', name='ck_rebar_bar_marks_non_negative'),
    sa.CheckConstraint('dia_mm > 0 AND count >= 0 AND pieces >= 1 AND lap_count >= 0', name='ck_rebar_bar_marks_positive'),
    sa.ForeignKeyConstraint(['element_id'], ['drawing_elements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['level_id'], ['building_levels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id', 'organization_id'], ['calculation_runs.id', 'calculation_runs.organization_id'], name='fk_rebar_bar_marks_run_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_row_id'], ['rebar_schedule_rows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solid_id', 'organization_id'], ['quantity_solids.id', 'quantity_solids.organization_id'], name='fk_rebar_bar_marks_solid_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_rebar_bar_marks_id_org'),
    sa.UniqueConstraint('run_id', 'solid_id', 'mark', name='uq_rebar_bar_marks_run_solid_mark')
    )
    op.create_index('ix_rebar_bar_marks_run_dia_grade', 'rebar_bar_marks', ['run_id', 'dia_mm', 'grade'], unique=False)
    op.create_index('ix_rebar_bar_marks_run_provenance', 'rebar_bar_marks', ['run_id', 'provenance'], unique=False)
    op.create_index('ix_rebar_bar_marks_run_solid', 'rebar_bar_marks', ['run_id', 'solid_id'], unique=False)
    op.create_table('staged_rebar_bar_marks',
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('solid_id', sa.UUID(), nullable=False),
    sa.Column('element_id', sa.UUID(), nullable=True),
    sa.Column('level_id', sa.UUID(), nullable=True),
    sa.Column('mark', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('shape_code', sa.String(length=40), nullable=False),
    sa.Column('shape_params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('designation', sa.String(length=20), nullable=True),
    sa.Column('dia_mm', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('grade', sa.String(length=30), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('spacing_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cut_len_mm', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('stock_len_mm', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('pieces', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('lap_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('lap_len_mm', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('total_len_m', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit_weight_kg_m', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_kg', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('provenance', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('review_status', sa.String(length=20), server_default='OK', nullable=False),
    sa.Column('schedule_row_id', sa.UUID(), nullable=True),
    sa.Column('trace', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('engine_version', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provenance <> 'RULE_ESTIMATE' OR review_status = 'REVIEW_REQUIRED'", name='ck_staged_rebar_bar_marks_estimate_needs_review'),
    sa.CheckConstraint("provenance IN ('IFC_EXACT','SCHEDULE_IMPORT','MANUAL','RULE_ESTIMATE')", name='ck_staged_rebar_bar_marks_provenance'),
    sa.CheckConstraint('cut_len_mm >= 0 AND total_len_m >= 0 AND total_kg >= 0', name='ck_staged_rebar_bar_marks_non_negative'),
    sa.ForeignKeyConstraint(['element_id'], ['drawing_elements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['level_id'], ['building_levels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id', 'organization_id'], ['calculation_runs.id', 'calculation_runs.organization_id'], name='fk_staged_rebar_bar_marks_run_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_row_id'], ['rebar_schedule_rows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['solid_id', 'organization_id'], ['staged_quantity_solids.id', 'staged_quantity_solids.organization_id'], name='fk_staged_rebar_bar_marks_solid_tenant', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_staged_rebar_bar_marks_run_stage', 'staged_rebar_bar_marks', ['run_id', 'stage'], unique=False)
    op.add_column('reinforcement_rules', sa.Column('stock_length_mm', sa.Numeric(precision=14, scale=3), nullable=True))
    op.add_column('reinforcement_rules', sa.Column('cover_mm', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('reinforcement_rules', sa.Column('min_lap_mm', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('reinforcement_rules', sa.Column('use_couplers', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('reinforcement_rules', sa.Column('weight_tolerance_pct', sa.Numeric(precision=6, scale=3), server_default='2.0', nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reinforcement_rules', 'weight_tolerance_pct')
    op.drop_column('reinforcement_rules', 'use_couplers')
    op.drop_column('reinforcement_rules', 'min_lap_mm')
    op.drop_column('reinforcement_rules', 'cover_mm')
    op.drop_column('reinforcement_rules', 'stock_length_mm')
    op.drop_index('ix_staged_rebar_bar_marks_run_stage', table_name='staged_rebar_bar_marks')
    op.drop_table('staged_rebar_bar_marks')
    op.drop_index('ix_rebar_bar_marks_run_solid', table_name='rebar_bar_marks')
    op.drop_index('ix_rebar_bar_marks_run_provenance', table_name='rebar_bar_marks')
    op.drop_index('ix_rebar_bar_marks_run_dia_grade', table_name='rebar_bar_marks')
    op.drop_table('rebar_bar_marks')
    op.drop_index('ix_rebar_schedule_rows_org_status', table_name='rebar_schedule_rows')
    op.drop_index('ix_rebar_schedule_rows_import', table_name='rebar_schedule_rows')
    op.drop_table('rebar_schedule_rows')
    op.drop_index('uq_rebar_shapes_system_code', table_name='rebar_shapes', postgresql_where=sa.text('organization_id IS NULL'))
    op.drop_index(op.f('ix_rebar_shapes_organization_id'), table_name='rebar_shapes')
    op.drop_index('ix_rebar_shapes_org', table_name='rebar_shapes')
    op.drop_table('rebar_shapes')
    op.drop_index('uq_bar_sizes_system_std_desig_grade', table_name='bar_sizes', postgresql_where=sa.text('organization_id IS NULL'))
    op.drop_index(op.f('ix_bar_sizes_organization_id'), table_name='bar_sizes')
    op.drop_index('ix_bar_sizes_org', table_name='bar_sizes')
    op.drop_table('bar_sizes')
    # ### end Alembic commands ###