"""finishes and schedules_3

Revision ID: 11192e0e2a28
Revises: c877036dd1f8
Create Date: 2026-10-04 20:01:32.232558
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '11192e0e2a28'
down_revision: Union[str, Sequence[str], None] = 'c877036dd1f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finish_rules', sa.Column('exclude', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    
    # ### end Alembic commands ###

def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finish_rules', 'exclude')
    # ### end Alembic commands ###