"""verification tables

Revision ID: 33e61acb2269
Revises: d37a00a51f16
Create Date: 2026-08-31 16:48:51.729553
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '33e61acb2269'
down_revision: Union[str, Sequence[str], None] = 'd37a00a51f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('boq_item_id', sa.UUID(), nullable=False),
    sa.Column('claim_date', sa.Date(), nullable=False),
    sa.Column('claimed_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('claimed_percentage', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='progress_claim_status'), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('claimed_percentage >= 0 AND claimed_percentage <= 100', name='ck_progress_claim_percentage_range'),
    sa.CheckConstraint('claimed_quantity > 0', name='ck_progress_claim_claimed_quantity_positive'),
    sa.ForeignKeyConstraint(['boq_item_id'], ['boq_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_claims_boq_item_id'), 'progress_claims', ['boq_item_id'], unique=False)
    op.create_index('ix_progress_claims_org_project', 'progress_claims', ['organization_id', 'project_id'], unique=False)
    op.create_index('ix_progress_claims_org_status', 'progress_claims', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_progress_claims_organization_id'), 'progress_claims', ['organization_id'], unique=False)
    op.create_index('ix_progress_claims_project_date', 'progress_claims', ['project_id', 'claim_date'], unique=False)
    op.create_index(op.f('ix_progress_claims_project_id'), 'progress_claims', ['project_id'], unique=False)
    op.create_index(op.f('ix_progress_claims_status'), 'progress_claims', ['status'], unique=False)
    op.create_table('photo_boq_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('progress_claim_id', sa.UUID(), nullable=False),
    sa.Column('site_photo_id', sa.UUID(), nullable=False),
    sa.Column('boq_item_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['boq_item_id'], ['boq_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['progress_claim_id'], ['progress_claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_photo_id'], ['site_photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('progress_claim_id', 'site_photo_id', 'boq_item_id', name='uq_photo_boq_link_claim_photo_boq')
    )
    op.create_index('ix_photo_boq_links_boq_item', 'photo_boq_links', ['boq_item_id'], unique=False)
    op.create_index('ix_photo_boq_links_claim', 'photo_boq_links', ['progress_claim_id'], unique=False)
    op.create_index('ix_photo_boq_links_org_project', 'photo_boq_links', ['organization_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_photo_boq_links_organization_id'), 'photo_boq_links', ['organization_id'], unique=False)
    op.create_index('ix_photo_boq_links_photo', 'photo_boq_links', ['site_photo_id'], unique=False)
    op.create_index(op.f('ix_photo_boq_links_project_id'), 'photo_boq_links', ['project_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_boq_links_project_id'), table_name='photo_boq_links')
    op.drop_index('ix_photo_boq_links_photo', table_name='photo_boq_links')
    op.drop_index(op.f('ix_photo_boq_links_organization_id'), table_name='photo_boq_links')
    op.drop_index('ix_photo_boq_links_org_project', table_name='photo_boq_links')
    op.drop_index('ix_photo_boq_links_claim', table_name='photo_boq_links')
    op.drop_index('ix_photo_boq_links_boq_item', table_name='photo_boq_links')
    op.drop_table('photo_boq_links')
    op.drop_index(op.f('ix_progress_claims_status'), table_name='progress_claims')
    op.drop_index(op.f('ix_progress_claims_project_id'), table_name='progress_claims')
    op.drop_index('ix_progress_claims_project_date', table_name='progress_claims')
    op.drop_index(op.f('ix_progress_claims_organization_id'), table_name='progress_claims')
    op.drop_index('ix_progress_claims_org_status', table_name='progress_claims')
    op.drop_index('ix_progress_claims_org_project', table_name='progress_claims')
    op.drop_index(op.f('ix_progress_claims_boq_item_id'), table_name='progress_claims')
    op.drop_table('progress_claims')
    # ### end Alembic commands ###