"""finishes and schedules_4

Revision ID: 353936bb5ca3
Revises: 11192e0e2a28
Create Date: 2026-10-05 03:41:25.414114
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '353936bb5ca3'
down_revision: Union[str, Sequence[str], None] = '11192e0e2a28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finish_rules', 'surface',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###

def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('finish_rules', 'surface',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###