"""notifications tables

Revision ID: 38564c862e0e
Revises: 22rp182326ah
Create Date: 2026-09-01 18:01:07.746952
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '38564c862e0e'
down_revision: Union[str, Sequence[str], None] = '22rp182326ah'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('DRAWING_PARSED', 'DRAWING_FAILED', 'BOQ_ITEM_APPROVED', 'SITE_PHOTO_NEEDS_PROJECT', 'PROGRESS_CLAIM_SUBMITTED', 'PROGRESS_CLAIM_APPROVED', 'PROGRESS_CLAIM_REJECTED', 'SUBSCRIPTION_USAGE_WARNING', 'MEMBER_JOINED', 'ORGANIZATION_INVITATION_RECEIVED', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link_path', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_org_user_read', 'notifications', ['organization_id', 'user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.alter_column('boq_items', 'item_type',
               existing_type=postgresql.ENUM('MATERIAL', 'LABOUR', 'CUSTOM', name='boq_item_type'),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_boq_items_item_type'), 'boq_items', ['item_type'], unique=False)
    op.alter_column('boq_versions', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'SUPERSEDED', name='boq_version_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('boq_versions', 'export_meta',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_boq_versions_status'), 'boq_versions', ['status'], unique=False)
    op.alter_column('labour_rates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('labour_rates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_labour_rates_organization_id'), 'labour_rates', ['organization_id'], unique=False)
    op.create_unique_constraint('uq_photo_tags_site_photo_tag', 'photo_tags', ['site_photo_id', 'tag'])
    op.add_column('whatsapp_messages', sa.Column('raw_payload', sa.JSON(), nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_messages', 'raw_payload')
    op.drop_constraint('uq_photo_tags_site_photo_tag', 'photo_tags', type_='unique')
    op.drop_index(op.f('ix_labour_rates_organization_id'), table_name='labour_rates')
    op.alter_column('labour_rates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('labour_rates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_boq_versions_status'), table_name='boq_versions')
    op.alter_column('boq_versions', 'export_meta',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               existing_nullable=False)
    op.alter_column('boq_versions', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'SUPERSEDED', name='boq_version_status'),
               server_default=sa.text("'ACTIVE'::boq_version_status"),
               existing_nullable=False)
    op.drop_index(op.f('ix_boq_items_item_type'), table_name='boq_items')
    op.alter_column('boq_items', 'item_type',
               existing_type=postgresql.ENUM('MATERIAL', 'LABOUR', 'CUSTOM', name='boq_item_type'),
               server_default=sa.text("'MATERIAL'::boq_item_type"),
               existing_nullable=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_index('ix_notifications_org_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###