"""subscription update tables

Revision ID: 3f9f4ac73ce0
Revises: 38564c862e0e
Create Date: 2026-09-02 06:51:55.417141
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '3f9f4ac73ce0'
down_revision: Union[str, Sequence[str], None] = '38564c862e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_projects_organization_code', 'projects', ['organization_id', 'code'])
    # ### end Alembic commands ###

def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_projects_organization_code', 'projects', type_='unique')
    # ### end Alembic commands ###