"""dra_boq_tables

Revision ID: 51d03f0a7d37
Revises: 2e44b9c9c326
Create Date: 2026-10-02 07:34:00.712015
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '51d03f0a7d37'
down_revision: Union[str, Sequence[str], None] = '2e44b9c9c326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boq_item_source_elements_element'), table_name='boq_item_source_elements')
    op.drop_index(op.f('ix_boq_item_source_elements_item'), table_name='boq_item_source_elements')
    op.alter_column('boq_versions', 'generation_meta',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.drop_index(op.f('ix_budget_categories_organization'), table_name='budget_categories')
    op.create_index(op.f('ix_budget_categories_organization_id'), 'budget_categories', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_change_order_line_items_order'), table_name='change_order_line_items')
    op.drop_index(op.f('ix_drawing_elements_ifc_global_id'), table_name='drawing_elements')
    op.drop_index(op.f('ix_material_normalization_cache_organization'), table_name='material_normalization_cache')
    op.drop_index(op.f('ix_material_normalization_cache_input_hash'), table_name='material_normalization_cache')
    op.create_index(op.f('ix_material_normalization_cache_input_hash'), 'material_normalization_cache', ['input_hash'], unique=False)
    op.create_index(op.f('ix_material_normalization_cache_organization_id'), 'material_normalization_cache', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_photo_tags_organization'), table_name='photo_tags')
    op.create_index(op.f('ix_photo_tags_organization_id'), 'photo_tags', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_retention_releases_agreement'), table_name='retention_releases')
    op.drop_index(op.f('ix_retention_releases_boq_version'), table_name='retention_releases')
    op.drop_index(op.f('ix_running_bill_line_items_bill'), table_name='running_bill_line_items')
    op.create_index('ix_site_logs_project', 'site_logs', ['project_id'], unique=False)
    op.drop_index(op.f('ix_subcontract_agreement_items_agreement'), table_name='subcontract_agreement_items')
    op.drop_index(op.f('ix_subcontractor_bill_line_items_bill'), table_name='subcontractor_bill_line_items')
    op.create_index(op.f('ix_work_items_organization_id'), 'work_items', ['organization_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_items_organization_id'), table_name='work_items')
    op.create_index(op.f('ix_subcontractor_bill_line_items_bill'), 'subcontractor_bill_line_items', ['bill_id'], unique=False)
    op.create_index(op.f('ix_subcontract_agreement_items_agreement'), 'subcontract_agreement_items', ['agreement_id'], unique=False)
    op.drop_index('ix_site_logs_project', table_name='site_logs')
    op.create_index(op.f('ix_running_bill_line_items_bill'), 'running_bill_line_items', ['bill_id'], unique=False)
    op.create_index(op.f('ix_retention_releases_boq_version'), 'retention_releases', ['boq_version_id'], unique=False)
    op.create_index(op.f('ix_retention_releases_agreement'), 'retention_releases', ['agreement_id'], unique=False)
    op.drop_index(op.f('ix_photo_tags_organization_id'), table_name='photo_tags')
    op.create_index(op.f('ix_photo_tags_organization'), 'photo_tags', ['organization_id'], unique=False)
    op.drop_index(op.f('ix_material_normalization_cache_organization_id'), table_name='material_normalization_cache')
    op.drop_index(op.f('ix_material_normalization_cache_input_hash'), table_name='material_normalization_cache')
    op.create_index(op.f('ix_material_normalization_cache_input_hash'), 'material_normalization_cache', ['input_hash'], unique=True)
    op.create_index(op.f('ix_material_normalization_cache_organization'), 'material_normalization_cache', ['organization_id'], unique=False)
    op.create_index(op.f('ix_drawing_elements_ifc_global_id'), 'drawing_elements', ['ifc_global_id'], unique=False)
    op.create_index(op.f('ix_change_order_line_items_order'), 'change_order_line_items', ['change_order_id'], unique=False)
    op.drop_index(op.f('ix_budget_categories_organization_id'), table_name='budget_categories')
    op.create_index(op.f('ix_budget_categories_organization'), 'budget_categories', ['organization_id'], unique=False)
    op.alter_column('boq_versions', 'generation_meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::json"))
    op.create_index(op.f('ix_boq_item_source_elements_item'), 'boq_item_source_elements', ['boq_item_id'], unique=False)
    op.create_index(op.f('ix_boq_item_source_elements_element'), 'boq_item_source_elements', ['drawing_element_id'], unique=False)
    # ### end Alembic commands ###