"""projects update tables

Revision ID: 58ec6f5dbe37
Revises: 3f9f4ac73ce0
Create Date: 2026-09-02 06:52:40.137977
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '58ec6f5dbe37'
down_revision: Union[str, Sequence[str], None] = '3f9f4ac73ce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###