"""engine_tables

Revision ID: 8c76d2c5890e
Revises: 69826ec2d649
Create Date: 2026-10-02 21:41:31.825149
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '8c76d2c5890e'
down_revision: Union[str, Sequence[str], None] = '69826ec2d649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_staged_quantity_ledger_id_org'), 'staged_quantity_ledger', type_='unique')
    # ### end Alembic commands ###

def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_staged_quantity_ledger_id_org'), 'staged_quantity_ledger', ['id', 'organization_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###