"""ai_requests tables

Revision ID: bb836ec0b1d2
Revises: a2768ef3bb9c
Create Date: 2026-09-02 18:58:24.878219
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'bb836ec0b1d2'
down_revision: Union[str, Sequence[str], None] = 'a2768ef3bb9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Enum('MATERIAL_NORMALIZATION', 'CAPTION_PARSING', 'PHOTO_TAGGING', name='ai_request_purpose'), nullable=False),
    sa.Column('entity_type', sa.Enum('DRAWING_ELEMENT', 'SITE_PHOTO', 'WHATSAPP_MESSAGE', name='ai_entity_type'), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Enum('OLLAMA', 'ANTHROPIC', name='ai_provider'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_requests_entity', 'ai_requests', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_ai_requests_org_created', 'ai_requests', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_ai_requests_org_purpose', 'ai_requests', ['organization_id', 'purpose'], unique=False)
    op.create_index(op.f('ix_ai_requests_organization_id'), 'ai_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_requests_purpose'), 'ai_requests', ['purpose'], unique=False)
    op.create_table('ai_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ai_request_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('SUCCEEDED', 'FAILED', name='ai_response_status'), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('parsed_output', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_request_id'], ['ai_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_request_id')
    )
    op.create_index(op.f('ix_ai_responses_status'), 'ai_responses', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_responses_status'), table_name='ai_responses')
    op.drop_table('ai_responses')
    op.drop_index(op.f('ix_ai_requests_purpose'), table_name='ai_requests')
    op.drop_index(op.f('ix_ai_requests_organization_id'), table_name='ai_requests')
    op.drop_index('ix_ai_requests_org_purpose', table_name='ai_requests')
    op.drop_index('ix_ai_requests_org_created', table_name='ai_requests')
    op.drop_index('ix_ai_requests_entity', table_name='ai_requests')
    op.drop_table('ai_requests')
    # ### end Alembic commands ###