"""add organization ai settings

Revision ID: c4c0383a7226
Revises: dc402fb8c6e6
Create Date: 2026-08-27 03:55:55.455297
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'c4c0383a7226'
down_revision: Union[str, Sequence[str], None] = 'dc402fb8c6e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('ai_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'ai_enabled')
    # ### end Alembic commands ###