"""finishes and schedules_2

Revision ID: c877036dd1f8
Revises: 1fce406782ae
Create Date: 2026-10-04 17:26:07.590053
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'c877036dd1f8'
down_revision: Union[str, Sequence[str], None] = '1fce406782ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drawing_elements', sa.Column('type_mark', sa.String(length=100), nullable=True))
    op.add_column('drawing_elements', sa.Column('type_name', sa.String(length=200), nullable=True))
    op.create_index('ix_drawing_elements_drawing_type_mark', 'drawing_elements', ['drawing_id', 'type_mark'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_drawing_elements_drawing_type_mark', table_name='drawing_elements')
    op.drop_column('drawing_elements', 'type_name')
    op.drop_column('drawing_elements', 'type_mark')
    # ### end Alembic commands ###