"""add whatsapp channels table v2

Revision ID: d37a00a51f16
Revises: f1369a779cc0
Create Date: 2026-08-30 20:53:03.107848
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'd37a00a51f16'
down_revision: Union[str, Sequence[str], None] = 'f1369a779cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('phone_number_id', sa.String(length=64), nullable=False),
    sa.Column('business_account_id', sa.String(length=64), nullable=False),
    sa.Column('display_phone_number', sa.String(length=32), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', name='uq_whatsapp_channels_organization'),
    sa.UniqueConstraint('phone_number_id', name='uq_whatsapp_channels_phone_number_id')
    )
    op.create_index(op.f('ix_whatsapp_channels_organization_id'), 'whatsapp_channels', ['organization_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_channels_phone_number_id'), 'whatsapp_channels', ['phone_number_id'], unique=False)
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('wa_message_id', sa.String(length=128), nullable=False),
    sa.Column('from_phone_number', sa.String(length=32), nullable=False),
    sa.Column('message_type', sa.Enum('IMAGE', 'TEXT', 'INTERACTIVE', 'OTHER', name='whatsapp_message_type'), nullable=False),
    sa.Column('caption_text', sa.Text(), nullable=True),
    sa.Column('media_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'MEDIA_DOWNLOADING', 'AWAITING_PROJECT_SELECTION', 'PROCESSED', 'FAILED', 'IGNORED', name='whatsapp_message_status'), nullable=False),
    sa.Column('prompt_wa_message_id', sa.String(length=128), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['whatsapp_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wa_message_id', name='uq_whatsapp_messages_wa_message_id')
    )
    op.create_index(op.f('ix_whatsapp_messages_channel_id'), 'whatsapp_messages', ['channel_id'], unique=False)
    op.create_index('ix_whatsapp_messages_org_status', 'whatsapp_messages', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_organization_id'), 'whatsapp_messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_prompt_wa_message_id'), 'whatsapp_messages', ['prompt_wa_message_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_status'), 'whatsapp_messages', ['status'], unique=False)
    op.create_table('site_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('whatsapp_message_id', sa.UUID(), nullable=True),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('sender_phone_number', sa.String(length=32), nullable=True),
    sa.Column('caption_raw', sa.Text(), nullable=True),
    sa.Column('caption_parsed', sa.JSON(), nullable=False),
    sa.Column('location_text', sa.String(length=500), nullable=True),
    sa.Column('photo_date', sa.Date(), nullable=True),
    sa.Column('is_ai_tagged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['whatsapp_message_id'], ['whatsapp_messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_message_id')
    )
    op.create_index('ix_site_photos_org_photo_date', 'site_photos', ['organization_id', 'photo_date'], unique=False)
    op.create_index('ix_site_photos_org_project', 'site_photos', ['organization_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_site_photos_organization_id'), 'site_photos', ['organization_id'], unique=False)
    op.create_index(op.f('ix_site_photos_project_id'), 'site_photos', ['project_id'], unique=False)
    op.create_table('photo_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_photo_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'AI', name='photo_tag_source'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_photo_id'], ['site_photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_photo_tags_site_photo', 'photo_tags', ['site_photo_id'], unique=False)
    op.create_index(op.f('ix_photo_tags_site_photo_id'), 'photo_tags', ['site_photo_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_tags_site_photo_id'), table_name='photo_tags')
    op.drop_index('ix_photo_tags_site_photo', table_name='photo_tags')
    op.drop_table('photo_tags')
    op.drop_index(op.f('ix_site_photos_project_id'), table_name='site_photos')
    op.drop_index(op.f('ix_site_photos_organization_id'), table_name='site_photos')
    op.drop_index('ix_site_photos_org_project', table_name='site_photos')
    op.drop_index('ix_site_photos_org_photo_date', table_name='site_photos')
    op.drop_table('site_photos')
    op.drop_index(op.f('ix_whatsapp_messages_status'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_prompt_wa_message_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_organization_id'), table_name='whatsapp_messages')
    op.drop_index('ix_whatsapp_messages_org_status', table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_channel_id'), table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_channels_phone_number_id'), table_name='whatsapp_channels')
    op.drop_index(op.f('ix_whatsapp_channels_organization_id'), table_name='whatsapp_channels')
    op.drop_table('whatsapp_channels')
    # ### end Alembic commands ###