"""Pricing and comparison

Revision ID: d65af0296dbe
Revises: 94607ee7dcee
Create Date: 2026-10-08 04:26:08.045784
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd65af0296dbe'
down_revision: Union[str, Sequence[str], None] = '94607ee7dcee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_rate_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('work_item_code', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_user_id', sa.UUID(), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(btrim(reason)) > 0', name='ck_project_rate_overrides_reason'),
    sa.CheckConstraint('effective_from IS NULL OR effective_to IS NULL OR effective_to >= effective_from', name='ck_project_rate_overrides_effective_range'),
    sa.CheckConstraint('rate >= 0', name='ck_project_rate_overrides_rate'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name='fk_project_rate_overrides_created_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revoked_by_user_id'], ['users.id'], name='fk_project_rate_overrides_revoked_by', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_project_rate_overrides_id_org')
    )
    op.create_index('ix_project_rate_overrides_org_project', 'project_rate_overrides', ['organization_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_project_rate_overrides_organization_id'), 'project_rate_overrides', ['organization_id'], unique=False)
    op.create_index('uq_project_rate_overrides_active', 'project_rate_overrides', ['project_id', 'work_item_code', 'unit'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('rate_books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('edition', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='PKR', nullable=False),
    sa.Column('jurisdiction', sa.String(length=50), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('immutable_version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_by_user_id', sa.UUID(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('parent_rate_book_id', sa.UUID(), nullable=True),
    sa.Column('supersedes_rate_book_id', sa.UUID(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status = 'DRAFT' OR published_at IS NOT NULL", name='ck_rate_books_published_at'),
    sa.CheckConstraint("status IN ('DRAFT','ACTIVE','SUPERSEDED','ARCHIVED')", name='ck_rate_books_status'),
    sa.CheckConstraint('char_length(currency) = 3', name='ck_rate_books_currency'),
    sa.CheckConstraint('effective_from IS NULL OR effective_to IS NULL OR effective_to >= effective_from', name='ck_rate_books_effective_range'),
    sa.CheckConstraint('immutable_version >= 1', name='ck_rate_books_version_pos'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_rate_book_id'], ['rate_books.id'], name='fk_rate_books_parent', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['published_by_user_id'], ['users.id'], name='fk_rate_books_published_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_rate_book_id'], ['rate_books.id'], name='fk_rate_books_supersedes', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_rate_books_id_org'),
    sa.UniqueConstraint('organization_id', 'code', 'immutable_version', name='uq_rate_books_org_code_version')
    )
    op.create_index('ix_rate_books_org', 'rate_books', ['organization_id'], unique=False)
    op.create_index(op.f('ix_rate_books_organization_id'), 'rate_books', ['organization_id'], unique=False)
    op.create_index('ix_rate_books_status', 'rate_books', ['status'], unique=False)
    op.create_index('uq_rate_books_active_org', 'rate_books', ['organization_id', 'code'], unique=True, postgresql_where=sa.text("status = 'ACTIVE' AND organization_id IS NOT NULL"))
    op.create_index('uq_rate_books_active_system', 'rate_books', ['code'], unique=True, postgresql_where=sa.text("status = 'ACTIVE' AND organization_id IS NULL"))
    op.create_index('uq_rate_books_system_code_version', 'rate_books', ['code', 'immutable_version'], unique=True, postgresql_where=sa.text('organization_id IS NULL'))
    op.create_table('rate_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rate_book_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('work_item_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('basis_quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('overhead_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('profit_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('computed_rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('basis_quantity > 0', name='ck_rate_analyses_basis'),
    sa.CheckConstraint('overhead_pct >= 0 AND profit_pct >= 0', name='ck_rate_analyses_pct'),
    sa.ForeignKeyConstraint(['rate_book_id', 'organization_id'], ['rate_books.id', 'rate_books.organization_id'], name='fk_rate_analyses_book_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rate_book_id'], ['rate_books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_rate_analyses_id_org'),
    sa.UniqueConstraint('rate_book_id', 'code', name='uq_rate_analyses_book_code')
    )
    op.create_index('ix_rate_analyses_book', 'rate_analyses', ['rate_book_id'], unique=False)
    op.create_index(op.f('ix_rate_analyses_organization_id'), 'rate_analyses', ['organization_id'], unique=False)
    op.create_index('ix_rate_analyses_work_item', 'rate_analyses', ['work_item_code'], unique=False)
    op.create_table('rate_book_escalations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rate_book_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('trade_scope', sa.String(length=80), server_default='ALL', nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('factor', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('factor > 0', name='ck_rate_book_escalations_factor'),
    sa.ForeignKeyConstraint(['rate_book_id', 'organization_id'], ['rate_books.id', 'rate_books.organization_id'], name='fk_rate_book_escalations_book_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rate_book_id'], ['rate_books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_book_id', 'trade_scope', 'effective_from', name='uq_rate_book_escalations_scope_date')
    )
    op.create_index('ix_rate_book_escalations_book', 'rate_book_escalations', ['rate_book_id'], unique=False)
    op.create_table('rate_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rate_book_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('work_item_code', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('trade', sa.String(length=80), nullable=True),
    sa.Column('specification', sa.Text(), nullable=True),
    sa.Column('csr_ref', sa.String(length=80), nullable=True),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rate >= 0', name='ck_rate_items_rate_non_negative'),
    sa.ForeignKeyConstraint(['analysis_id'], ['rate_analyses.id'], name='fk_rate_items_analysis_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['rate_book_id', 'organization_id'], ['rate_books.id', 'rate_books.organization_id'], name='fk_rate_items_book_tenant', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rate_book_id'], ['rate_books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_book_id', 'work_item_code', 'unit', name='uq_rate_items_book_code_unit')
    )
    op.create_index('ix_rate_items_book', 'rate_items', ['rate_book_id'], unique=False)
    op.create_index(op.f('ix_rate_items_organization_id'), 'rate_items', ['organization_id'], unique=False)
    op.create_index('ix_rate_items_work_item', 'rate_items', ['work_item_code'], unique=False)
    op.create_table('rate_analysis_components',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('work_item_code', sa.String(length=50), nullable=True),
    sa.Column('rate_source', sa.String(length=20), nullable=False),
    sa.Column('ref_rate_item_id', sa.UUID(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('coefficient', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('unit_rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("component_type IN ('MATERIAL','LABOUR','PLANT','OTHER')", name='ck_rate_analysis_components_type'),
    sa.CheckConstraint("rate_source <> 'DIRECT' OR unit_rate IS NOT NULL", name='ck_rate_analysis_components_direct_has_rate'),
    sa.CheckConstraint("rate_source <> 'RATE_ITEM' OR ref_rate_item_id IS NOT NULL", name='ck_rate_analysis_components_ref_has_item'),
    sa.CheckConstraint("rate_source IN ('DIRECT','RATE_ITEM','LABOUR_RATE','MATERIAL_LIBRARY')", name='ck_rate_analysis_components_source'),
    sa.CheckConstraint('coefficient >= 0', name='ck_rate_analysis_components_coefficient'),
    sa.ForeignKeyConstraint(['analysis_id'], ['rate_analyses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ref_rate_item_id'], ['rate_items.id'], name='fk_rate_analysis_components_ref_item', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id', 'sequence', name='uq_rate_analysis_components_seq')
    )
    op.create_index('ix_rate_analysis_components_analysis', 'rate_analysis_components', ['analysis_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rate_analysis_components_analysis', table_name='rate_analysis_components')
    op.drop_table('rate_analysis_components')
    op.drop_index('ix_rate_items_work_item', table_name='rate_items')
    op.drop_index(op.f('ix_rate_items_organization_id'), table_name='rate_items')
    op.drop_index('ix_rate_items_book', table_name='rate_items')
    op.drop_table('rate_items')
    op.drop_index('ix_rate_book_escalations_book', table_name='rate_book_escalations')
    op.drop_table('rate_book_escalations')
    op.drop_index('ix_rate_analyses_work_item', table_name='rate_analyses')
    op.drop_index(op.f('ix_rate_analyses_organization_id'), table_name='rate_analyses')
    op.drop_index('ix_rate_analyses_book', table_name='rate_analyses')
    op.drop_table('rate_analyses')
    op.drop_index('uq_rate_books_system_code_version', table_name='rate_books', postgresql_where=sa.text('organization_id IS NULL'))
    op.drop_index('uq_rate_books_active_system', table_name='rate_books', postgresql_where=sa.text("status = 'ACTIVE' AND organization_id IS NULL"))
    op.drop_index('uq_rate_books_active_org', table_name='rate_books', postgresql_where=sa.text("status = 'ACTIVE' AND organization_id IS NOT NULL"))
    op.drop_index('ix_rate_books_status', table_name='rate_books')
    op.drop_index(op.f('ix_rate_books_organization_id'), table_name='rate_books')
    op.drop_index('ix_rate_books_org', table_name='rate_books')
    op.drop_table('rate_books')
    op.drop_index('uq_project_rate_overrides_active', table_name='project_rate_overrides', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index(op.f('ix_project_rate_overrides_organization_id'), table_name='project_rate_overrides')
    op.drop_index('ix_project_rate_overrides_org_project', table_name='project_rate_overrides')
    op.drop_table('project_rate_overrides')
    # ### end Alembic commands ###