"""create whatsapp tables

Revision ID: f1369a779cc0
Revises: f9eb2fc8da4a
Create Date: 2026-08-30 17:24:03.557027
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'f1369a779cc0'
down_revision: Union[str, Sequence[str], None] = 'f9eb2fc8da4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###