"""drawings_boq tables

Revision ID: f9eb2fc8da4a
Revises: b887a319b1db
Create Date: 2026-08-29 18:58:53.394650
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'f9eb2fc8da4a'
down_revision: Union[str, Sequence[str], None] = 'b887a319b1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_normalization_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_normalization_cache_input_hash'), 'material_normalization_cache', ['input_hash'], unique=True)
    op.create_table('material_library',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('default_unit', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'raw_text', name='uq_material_library_org_raw_text')
    )
    op.create_index('ix_material_library_org', 'material_library', ['organization_id'], unique=False)
    op.create_index(op.f('ix_material_library_organization_id'), 'material_library', ['organization_id'], unique=False)
    op.create_table('drawings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('format', sa.Enum('IFC', 'DWG', 'DXF', 'RVT', name='drawing_format'), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'PARSED', 'FAILED', name='drawing_status'), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drawings_org_project', 'drawings', ['organization_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_drawings_organization_id'), 'drawings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_drawings_project_id'), 'drawings', ['project_id'], unique=False)
    op.create_index(op.f('ix_drawings_status'), 'drawings', ['status'], unique=False)
    op.create_table('boq_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('drawing_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_boq_versions_org_project', 'boq_versions', ['organization_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_boq_versions_organization_id'), 'boq_versions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_boq_versions_project_id'), 'boq_versions', ['project_id'], unique=False)
    op.create_table('drawing_elements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drawing_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('ifc_global_id', sa.String(length=64), nullable=True),
    sa.Column('ifc_type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('raw_material_text', sa.String(length=500), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_drawing_elements_drawing', 'drawing_elements', ['drawing_id'], unique=False)
    op.create_index(op.f('ix_drawing_elements_drawing_id'), 'drawing_elements', ['drawing_id'], unique=False)
    op.create_index(op.f('ix_drawing_elements_organization_id'), 'drawing_elements', ['organization_id'], unique=False)
    op.create_table('boq_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('boq_version_id', sa.UUID(), nullable=False),
    sa.Column('drawing_element_id', sa.UUID(), nullable=True),
    sa.Column('material_name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=150), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', name='boq_item_status'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['boq_version_id'], ['boq_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drawing_element_id'], ['drawing_elements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boq_items_boq_version_id'), 'boq_items', ['boq_version_id'], unique=False)
    op.create_index('ix_boq_items_org_status', 'boq_items', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_boq_items_organization_id'), 'boq_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_boq_items_status'), 'boq_items', ['status'], unique=False)
    op.create_index('ix_boq_items_version', 'boq_items', ['boq_version_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
  # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_boq_items_version', table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_status'), table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_organization_id'), table_name='boq_items')
    op.drop_index('ix_boq_items_org_status', table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_boq_version_id'), table_name='boq_items')
    op.drop_table('boq_items')
    op.drop_index(op.f('ix_drawing_elements_organization_id'), table_name='drawing_elements')
    op.drop_index(op.f('ix_drawing_elements_drawing_id'), table_name='drawing_elements')
    op.drop_index('ix_drawing_elements_drawing', table_name='drawing_elements')
    op.drop_table('drawing_elements')
    op.drop_index(op.f('ix_boq_versions_project_id'), table_name='boq_versions')
    op.drop_index(op.f('ix_boq_versions_organization_id'), table_name='boq_versions')
    op.drop_index('ix_boq_versions_org_project', table_name='boq_versions')
    op.drop_table('boq_versions')
    op.drop_index(op.f('ix_drawings_status'), table_name='drawings')
    op.drop_index(op.f('ix_drawings_project_id'), table_name='drawings')
    op.drop_index(op.f('ix_drawings_organization_id'), table_name='drawings')
    op.drop_index('ix_drawings_org_project', table_name='drawings')
    op.drop_table('drawings')
    op.drop_index(op.f('ix_material_library_organization_id'), table_name='material_library')
    op.drop_index('ix_material_library_org', table_name='material_library')
    op.drop_table('material_library')
    op.drop_index(op.f('ix_material_normalization_cache_input_hash'), table_name='material_normalization_cache')
    op.drop_table('material_normalization_cache')
    # ### end Alembic commands ###